# Generated by Django 2.2.5 on 2019-09-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtered_data',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='raw_data',
            old_name='category_id',
            new_name='category',
        ),
    ]
