# Generated by Django 2.2.5 on 2019-09-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_data',
            old_name='contents',
            new_name='content',
        ),
    ]
