# Generated by Django 2.2.5 on 2019-09-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190927_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_party_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
